" Generated by vim-autofmt-gen
" This can be overwritten so you should change only flags (0 or 1)
{% for key, value in _dict.items() %}
  {%- for plugin in value %}
    {%- if loop.index <= 1 %}
let g:autofmtgen_{{ key }}_{{ plugin }}_skip = 0
    {%- else %}
let g:autofmtgen_{{ key }}_{{ plugin }}_skip = 1
    {%- endif %}
  {%- endfor %}
{%- endfor %}
